#!/bin/bash
#
##-------------------------------
# Server start script
# Author: esdf
# Usage: ./qlrc <ruleset> <country> <mode> <map> <pass> <name>
# Supported country codes [ EU ONLY SO FAR ]: de nl fr uk se
# Gametype codes: duel tdm ctf (ca & ft not tried yet)
##-------------------------------

##-------------------------------
# LET'S GO!!!
##-------------------------------
ruleset=$1
ccode=$2
gmode=$3
map=$4
pass=$5
svname=$6

printf "Requested server: $svname [$ruleset $gmode/$ccode on $map (pw: $pass)]\n"

defvalues="capture_limit=8&time_limit=20&sv_maxclients=24&g_instagib=0&g_spawnarmor=1&players_slots=32&mercylimit=0&premium=1&web_callVoteOptions=1&g_gravity=800&web_instantWeaponSwitch=0&g_forceDmgThroughSurface=0&g_quadDamageFactor=3&round_limit=10&pmove_RampJump=0&map_tag=&g_timeoutCount=5&g_timeoutLen=120&access=public&teamsize=4&g_spawnItemPowerup=1"

##-------------------------------
# DEFINE FNS
##-------------------------------
ropts () {
	case $ccode in
		"de") ccode=18;;
		"nl") ccode=17;;
		"fr") ccode=20;;
		"uk") ccode=19;;
		"se") ccode=29;;
		*) printf "You did something wrong, retry with correct parameters.";;
	esac
	
	case $ruleset in
		"vql") srv 1;;
		"pql") srv 2;;
		*) printf "You did something wrong, retry with correct parameters.";;
	esac
}

getlinks () {
        qlstoken=$(jshon -e TOKEN -u < token)
	let count=0
	while [ -z $qlsinv ]; do
		sleep 3 # Waiting 3 seconds to avoid overload
		((count++)) # Just a little process-counting
		curl -s -b login -A "Mozilla/4.0" http://www.quakelive.com/request/status?token=$qlstoken | jshon > svinfo
		printf "($count) Waiting for spawn...\r" # To show that something is happening
		if [ -e svinfo ]; then
		 qlsinv=$(jshon -e SERVER_INFO -e INVITATION_CODE -u < svinfo)
		 qlsid=$(jshon -e SERVER_INFO -e SERVER_ID -u < svinfo)
		fi
	done
	printf "Invite link: http://www.quakelive.com/r/join/$qlsinv\n"
	printf "Short link: http://www.quakelive.com/r/join/$qlsid\n"
	rm svinfo
	rm token
}

srv () {
	curl -s -b login -d "location=$ccode&gametype=$gmode&arenas=$map&g_password=$pass&sv_hostname=$svname&ruleset=$1&$defvalues" -A "Mozilla/4.0" http://www.quakelive.com/request/start | jshon > token
	getlinks
}

##-------------------------------
# LIFTOFF !!!
##-------------------------------
ropts
exit 0
